### ISSUE TITLE
Doesn't work in Chrome, undefined profile

### ISSUE THREAD

**Issue by Nitrocosm** [flyinggiants/ScoreSaber-Rank-Panel#3]
When I tried to set up the extension, it kept telling me "Welcome undefined!" and wouldn't load my profile. I tried it with even more profiles and I got the same result.

**Comment by LucaVazz** [comment]
Hey @Nitrocosm,

thanks for reaching out!

I've just released a new version of the extension that fixes this error, everything should work fine again now.
